#!/usr/bin/env nextflow

nextflow.enable.dsl=2

//##############################3
//## Extract overlapping EPIC sites for methylation based classification 
//#############################

//# wf_mods_bedmethyl generated by modkit in Epi2me-labs on the P24
//# EPIC_sites_NEW.bed contains chromosomal coordinates and names of EPIC 850 probes
//# Uses Bedtools intersect, awk and sed


//epi2me pipeline to run modkit

process run_epi2me_modkit {
    label 'modkit'
    cpus 6
    memory '16 GB'
    publishDir "${params.path}/results/epi2me/modkit/", mode: "copy", overwrite: true

    input:
    tuple val(sample_id), path(bam), path(bai), path(reference_genome), path(reference_genome_bai), path(epimodkit)

    output:
    tuple val(sample_id), path("${sample_id}.wf_mods.bedmethyl.gz")

    script:
    """
    export PATH=/opt/custflow/epi2meuser/conda/bin:\$PATH
    
    # Check if modkit is available
    which modkit || echo "modkit not found in PATH"
    
    # Check if input files exist
    if [ ! -f "${bam}" ]; then
        echo "ERROR: BAM file not found: ${bam}"
        exit 1
    fi
    
    if [ ! -f "${reference_genome}" ]; then
        echo "ERROR: Reference genome not found: ${reference_genome}"
        exit 1
    fi
    
    modkit pileup \
      ${bam} \
      ${sample_id}.wf_mods.bedmethyl \
      --ref ${reference_genome} \
      --interval-size ${params.interval_size} \
      --log-filepath ${sample_id}_modkit.log

    gzip ${sample_id}.wf_mods.bedmethyl
    
    # Check if output was created
    ls -la ${sample_id}.wf_mods.bedmethyl.gz
    """
}


//epi2me pipeline to run sv with sniffles2 with mosaic option

process run_epi2me_sv {
    cpus 4
    memory '16 GB'
    label 'pipeline1'
   publishDir "${params.path}/results/epi2me/episv/", mode: "copy", overwrite: true

    input:
  tuple val(sample_id), path(bam), path(bai)

    output:
  tuple val(sample_id), path("${sample_id}.vcf.gz"), path("${sample_id}.vcf.gz.tbi"), emit: svvcf

    script:
    """
  # Check if sniffles is available
  which sniffles || echo "sniffles not found in PATH"
  
  # Check if input file exists
  if [ ! -f "${bam}" ]; then
      echo "ERROR: BAM file not found: ${bam}"
      exit 1
  fi
  
  # Run Sniffles2
  sniffles --input ${bam} --vcf ${sample_id}.vcf.gz
  
  # Check if output was created
  ls -la ${sample_id}.vcf.gz
  
  # Index the VCF file (commented out for now)
  #tabix -p vcf ${sample_id}.vcf.gz
    """
}
//epi2me pipeline to run cnv qdnaseq
process run_epi2me_cnv {
    cpus 4
    memory '8 GB'
    label 'epi2me'
  publishDir "${params.path}/results/epi2me/epicnv/", mode: "copy", overwrite: true

    input:
  tuple val(sample_id), path(bam), path(bai), path(reference_genome), path(reference_genome_bai), path(epicnv)

    output:
  tuple val(sample_id), path("${sample_id}_segs.bed"), path("${sample_id}_bins.bed"), path("${sample_id}_segs.vcf"), path("${sample_id}_copyNumbersCalled.rds"), path("${sample_id}_calls.bed"), path("${sample_id}_calls.vcf"), path("${sample_id}_raw_bins.bed"), path("${sample_id}_plots.pdf"), path("${sample_id}_isobar_plot.png"), path("${sample_id}_cov.png")
    
    script:
    """
  export R_HOME=/usr/local/lib/R
  echo R_HOME: \$R_HOME
  
  # Check if Rscript is available
  which Rscript || echo "Rscript not found in PATH"
  
  # Check if the R script exists
  if [ ! -f "/home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/bin/run_qdnaseq_rds.r" ]; then
      echo "ERROR: R script not found"
      exit 1
  fi

  Rscript --vanilla /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/bin/run_qdnaseq_rds.r \
    --bam ${bam} \
    --binsize ${params.binsize} \
    --out_prefix ${sample_id}
    
  # Check if output files were created
  ls -la ${sample_id}_*
    """
}



workflow epi2me {
    take:
        merged_data
        
    main:
        params.run_mode = params.run_mode_epi2me ?: 'all'
        println "epi2me run mode: ${params.run_mode}"

        // Validate required parameters
        if (!params.reference_genome) {
            error "ERROR: Reference genome path not specified (params.reference_genome)"
        }
        if (!params.reference_genome_bai) {
            error "ERROR: Reference genome index path not specified (params.reference_genome_bai)"
        }

        // Create file objects for reference files
        reference_genome = file(params.reference_genome)
        reference_genome_bai = file(params.reference_genome_bai)
        episv = file(params.episv)
        epimodkit = file(params.epimodkit)
        epicnv = file(params.epicnv)    

        // Validate reference files exist
        if (!reference_genome.exists()) {
            error "ERROR: Reference genome file not found: ${params.reference_genome}"
        }
        if (!reference_genome_bai.exists()) {
            error "ERROR: Reference genome index file not found: ${params.reference_genome_bai}"
        }

        // Validate run_mode parameter
        if (!['modkit', 'cnv', 'sv', 'all'].contains(params.run_mode)) {
            error "ERROR: Invalid run_mode '${params.run_mode}' for epi2me. Valid modes: modkit, cnv, sv, all."
        }

        // Create input channel based on run mode
        input_channel = params.run_order_mode ? 
            merged_data.map { sid, bam, bai -> 
                tuple(
                    sid, 
                    bam, 
                    bai,
                    reference_genome,
                    reference_genome_bai
                )
            } : Channel
            .from(file(params.epi2me_sample_id_file).readLines())
            .map { line ->
                def fields = line.tokenize("\t")
                def sample_id = fields[0].trim()
                def bam = file("${params.merge_bam_folder}/${sample_id}.*.bam")
                def bai = file("${params.merge_bam_folder}/${sample_id}.*.bam.bai")

                bam = bam.find()
                bai = bai.find()

                if (!bam || !bai) {
                    error "BAM file or index file not found for sample ID: ${sample_id}"
                }

                return tuple(
                    sample_id, 
                    bam, 
                    bai,
                    reference_genome,
                    reference_genome_bai
                )
            }

        // Run processes based on mode
        modkit_ch = Channel.empty()
        cnv_ch = Channel.empty()
        sv_ch = Channel.empty()

        if (params.run_mode in ['modkit', 'all']) {
            println "Running modkit..."
            modkit_ch = input_channel.map { sid, bam, bai, ref, ref_bai ->
                tuple(
                    sid, 
                    bam, 
                    bai, 
                    ref, 
                    ref_bai, 
                    file("${params.epimodkit}")
                )
            } | run_epi2me_modkit
        }

        if (params.run_mode in ['cnv', 'all']) {
            println "Running cnv..."
            cnv_ch = input_channel.map { sid, bam, bai, ref, ref_bai ->
                tuple(
                    sid, 
                    bam, 
                    bai, 
                    ref, 
                    ref_bai, 
                    file("${params.epicnv}")
                )
            } | run_epi2me_cnv
        }

        if (params.run_mode in ['sv', 'all']) {
            println "Running sv..."
            sv_ch = input_channel.map { sid, bam, bai, ref, ref_bai ->
                tuple(
                    sid, 
                    bam, 
                    bai
                )
            } | run_epi2me_sv
            
            // Wait for SV completion
    
        }

        // Create default channels for empty processes
        default_modkit = input_channel.map { sid, bam, bai, ref, ref_bai -> 
            tuple(sid, file("${params.epimodkit}/${sid}.wf_mods.bedmethyl.gz")) 
        }
        
        default_cnv = input_channel.map { sid, bam, bai, ref, ref_bai -> 
            tuple(
                sid, 
                file("${params.epicnv}/qdna_seq/${sid}_segs.bed"),
                file("${params.epicnv}/qdna_seq/${sid}_bins.bed"),
                file("${params.epicnv}/qdna_seq/${sid}_segs.vcf")
            )
        }
        
        default_sv = input_channel.map { sid, bam, bai, ref, ref_bai -> 
            tuple(sid, file("${params.episv}/${sid}.wf_sv.vcf.gz"))
        }

        // Mix actual results with defaults
        modkit_results = modkit_ch.mix(default_modkit)
        cnv_results = cnv_ch.mix(default_cnv)
        sv_results = sv_ch.mix(default_sv)

        // Combine all results
        results_ch = input_channel
            .join(modkit_results, by: 0)
            .join(cnv_results, by: 0)
            .join(sv_results, by: 0)
            .map { sample_id, bam, bai, ref, ref_bai, modkit, segs_bed, bins_bed, segs_vcf, sv ->
                log.info "Processing completed for sample: ${sample_id}"
                tuple(
                    sample_id,
                    modkit,
                    segs_bed,
                    bins_bed,
                    segs_vcf,
                    sv
                )
            }

    emit:
        results = results_ch
            .map { results ->
                log.info "Epi2me processing completed for sample: ${results[0]}"
                results
            }
}