#!/usr/bin/env nextflow

nextflow.enable.dsl=2

//##############################3
//## Extract overlapping EPIC sites for methylation based classification 
//#############################

//# wf_mods_bedmethyl generated by modkit in Epi2me-labs on the P24
//# EPIC_sites_NEW.bed contains chromosomal coordinates and names of EPIC 850 probes
//# Uses Bedtools intersect, awk and sed


//epi2me pipeline to run modkit

process run_epi2me_modkit {
    label 'modkit'
    cpus 6
    memory '16 GB'
    publishDir "${params.path}/results/epi2me/modkit/", mode: "copy", overwrite: true

    input:
    tuple val(sample_id), path(bam), path(bai), path(reference_genome), path(reference_genome_bai), path(epimodkit)

    output:
    tuple val(sample_id), path("${sample_id}.wf_mods.bedmethyl.gz")

    script:
    """
    export PATH=/opt/custflow/epi2meuser/conda/bin:\$PATH
    modkit pileup \
      ${bam} \
      --region chr1:1-1000000 \
      ${sample_id}.wf_mods.bedmethyl \
      --ref ${reference_genome} \
      --interval-size ${params.interval_size} \
      --log-filepath ${sample_id}_modkit.log

    gzip ${sample_id}.wf_mods.bedmethyl
    """
}


//epi2me pipeline to run sv with sniffles2 with mosaic option

process run_epi2me_sv {
  cpus 4
  memory '16 GB'
  label 'pipeline1'
   publishDir "${params.path}/results/epi2me/episv/", mode: "copy", overwrite: true

  input:
  tuple val(sample_id), path(bam), path(bai)

  output:
  tuple val(sample_id), path("${sample_id}.vcf.gz"), path("${sample_id}.vcf.gz.tbi"), emit: svvcf

  script:
  """
  # Example: directly run Sniffles2
  sniffles --input ${bam} --vcf ${sample_id}.vcf.gz
  
  # Index the VCF file
  #tabix -p vcf ${sample_id}.vcf.gz
  """
}
//epi2me pipeline to run cnv qdnaseq
process run_epi2me_cnv {
  cpus 4
  memory '8 GB'
  label 'epi2me'
  publishDir "${params.path}/results/epi2me/epicnv/", mode: "copy", overwrite: true

  input:
  tuple val(sample_id), path(bam), path(bai), path(reference_genome), path(reference_genome_bai), path(tr_bed_file), path(epicnv)

  output:
  tuple val(sample_id), path("${sample_id}_*")

  script:
  """
  export R_HOME=/usr/local/lib/R
  echo R_HOME: \$R_HOME

  Rscript --vanilla /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/bin/run_qdnaseq_rds.r \
    --bam ${bam} \
    --binsize ${params.binsize} \
    --out_prefix ${sample_id}
  """
}



workflow epi2me {
    take:
        merged_data
        
    main:
        params.run_mode = params.run_mode_epi2me ?: 'all'
        println "epi2me run mode: ${params.run_mode}"

        // Validate required parameters
        if (!params.reference_genome) {
            error "ERROR: Reference genome path not specified (params.reference_genome)"
        }
        if (!params.reference_genome_bai) {
            error "ERROR: Reference genome index path not specified (params.reference_genome_bai)"
        }
        if (!params.tr_bed_file) {
            error "ERROR: TR BED file path not specified (params.tr_bed_file)"
        }

        // Create file objects for reference files
        reference_genome = file(params.reference_genome)
        reference_genome_bai = file(params.reference_genome_bai)
        tr_bed_file = file(params.tr_bed_file)
        episv = file(params.episv)
        epimodkit = file(params.epimodkit)
        epicnv = file(params.epicnv)    

        // Validate reference files exist
        if (!reference_genome.exists()) {
            error "ERROR: Reference genome file not found: ${params.reference_genome}"
        }
        if (!reference_genome_bai.exists()) {
            error "ERROR: Reference genome index file not found: ${params.reference_genome_bai}"
        }
        if (!tr_bed_file.exists()) {
            error "ERROR: TR BED file not found: ${params.tr_bed_file}"
        }

        // Validate run_mode parameter
        if (!['modkit', 'cnv', 'sv', 'all'].contains(params.run_mode)) {
            error "ERROR: Invalid run_mode '${params.run_mode}' for epi2me. Valid modes: modkit, cnv, sv, all."
        }

        // Create input channel based on run mode
        input_channel = params.run_order_mode ? 
            merged_data.map { sid, bam, bai -> 
                tuple(
                    sid, 
                    bam, 
                    bai,
                    reference_genome,
                    reference_genome_bai,
                    tr_bed_file
                )
            } : Channel
            .from(file(params.epi2me_sample_id_file).readLines())
            .map { line ->
                def fields = line.tokenize("\t")
                def sample_id = fields[0].trim()
                def bam = file("${params.merge_bam_folder}/${sample_id}.*.bam")
                def bai = file("${params.merge_bam_folder}/${sample_id}.*.bam.bai")

                bam = bam.find()
                bai = bai.find()

                if (!bam || !bai) {
                    error "BAM file or index file not found for sample ID: ${sample_id}"
                }

                return tuple(
                    sample_id, 
                    bam, 
                    bai,
                    reference_genome,
                    reference_genome_bai,
                    tr_bed_file
                )
            }

        // Run processes based on mode
        modkit_ch = Channel.empty()
        cnv_ch = Channel.empty()
        sv_ch = Channel.empty()

        if (params.run_mode in ['modkit', 'all']) {
            println "Running modkit..."
            modkit_ch = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed ->
                tuple(
                    sid, 
                    bam, 
                    bai, 
                    ref, 
                    ref_bai, 
                    tr_bed, 
                    file("${params.epimodkit}")
                )
            } | run_epi2me_modkit
        }

        if (params.run_mode in ['cnv', 'all']) {
            println "Running cnv..."
            cnv_ch = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed ->
                tuple(
                    sid, 
                    bam, 
                    bai, 
                    ref, 
                    ref_bai, 
                    tr_bed, 
                    file("${params.epicnv}")
                )
            } | run_epi2me_cnv
        }

        if (params.run_mode in ['sv', 'all']) {
            println "Running sv..."
            sv_ch = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed ->
                tuple(
                    sid, 
                    bam, 
                    bai, 
                    ref, 
                    ref_bai, 
                    tr_bed, 
                    file("${params.episv}")
                )
            } | run_epi2me_sv
            
            // Wait for SV completion
    
        }

        // Create default channels for empty processes
        default_modkit = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed -> 
            tuple(sid, file("${params.epimodkit}/${sid}.wf_mods.bedmethyl.gz")) 
        }
        
        default_cnv = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed -> 
            tuple(
                sid, 
                file("${params.epicnv}/qdna_seq/${sid}_segs.bed"),
                file("${params.epicnv}/qdna_seq/${sid}_bins.bed"),
                file("${params.epicnv}/qdna_seq/${sid}_segs.vcf")
            )
        }
        
        default_sv = input_channel.map { sid, bam, bai, ref, ref_bai, tr_bed -> 
            tuple(sid, file("${params.episv}/${sid}.wf_sv.vcf.gz"))
        }

        // Mix actual results with defaults
        modkit_results = modkit_ch.mix(default_modkit)
        cnv_results = cnv_ch.mix(default_cnv)
        sv_results = sv_ch.mix(default_sv)

        // Combine all results
        results_ch = input_channel
            .join(modkit_results, by: 0)
            .join(cnv_results, by: 0)
            .join(sv_results, by: 0)
            .map { sample_id, bam, bai, ref, ref_bai, tr_bed, modkit, segs_bed, bins_bed, segs_vcf, sv ->
                log.info "Processing completed for sample: ${sample_id}"
                tuple(
                    sample_id,
                    modkit,
                    segs_bed,
                    bins_bed,
                    segs_vcf,
                    sv
                )
            }

    emit:
        results = results_ch
            .map { results ->
                log.info "Epi2me processing completed for sample: ${results[0]}"
                results
            }
}